// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package service is a generated GoMock package.
package service_test

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDBRepo is a mock of DBRepo interface.
type MockDBRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDBRepoMockRecorder
}

// MockDBRepoMockRecorder is the mock recorder for MockDBRepo.
type MockDBRepoMockRecorder struct {
	mock *MockDBRepo
}

// NewMockDBRepo creates a new mock instance.
func NewMockDBRepo(ctrl *gomock.Controller) *MockDBRepo {
	mock := &MockDBRepo{ctrl: ctrl}
	mock.recorder = &MockDBRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBRepo) EXPECT() *MockDBRepoMockRecorder {
	return m.recorder
}

// GetPeerFollows mocks base method.
func (m *MockDBRepo) GetPeerFollows(initiator string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeerFollows", initiator)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeerFollows indicates an expected call of GetPeerFollows.
func (mr *MockDBRepoMockRecorder) GetPeerFollows(initiator interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeerFollows", reflect.TypeOf((*MockDBRepo)(nil).GetPeerFollows), initiator)
}

// GetWhoFollowsPeer mocks base method.
func (m *MockDBRepo) GetWhoFollowsPeer(initiator string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWhoFollowsPeer", initiator)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWhoFollowsPeer indicates an expected call of GetWhoFollowsPeer.
func (mr *MockDBRepoMockRecorder) GetWhoFollowsPeer(initiator interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWhoFollowsPeer", reflect.TypeOf((*MockDBRepo)(nil).GetWhoFollowsPeer), initiator)
}

// InvitePeer mocks base method.
func (m *MockDBRepo) InvitePeer(initiator, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvitePeer", initiator, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvitePeer indicates an expected call of InvitePeer.
func (mr *MockDBRepoMockRecorder) InvitePeer(initiator, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvitePeer", reflect.TypeOf((*MockDBRepo)(nil).InvitePeer), initiator, email)
}

// RemoveSubscribe mocks base method.
func (m *MockDBRepo) RemoveSubscribe(peer1, peer2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSubscribe", peer1, peer2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSubscribe indicates an expected call of RemoveSubscribe.
func (mr *MockDBRepoMockRecorder) RemoveSubscribe(peer1, peer2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSubscribe", reflect.TypeOf((*MockDBRepo)(nil).RemoveSubscribe), peer1, peer2)
}

// SetFriend mocks base method.
func (m *MockDBRepo) SetFriend(peer1, peer2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFriend", peer1, peer2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetFriend indicates an expected call of SetFriend.
func (mr *MockDBRepoMockRecorder) SetFriend(peer1, peer2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFriend", reflect.TypeOf((*MockDBRepo)(nil).SetFriend), peer1, peer2)
}
